In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import datetime

In [5]:
import gensim.downloader


In [7]:
print(list(gensim.downloader.info()['models'].keys()))

['fasttext-wiki-news-subwords-300', 'conceptnet-numberbatch-17-06-300', 'word2vec-ruscorpora-300', 'word2vec-google-news-300', 'glove-wiki-gigaword-50', 'glove-wiki-gigaword-100', 'glove-wiki-gigaword-200', 'glove-wiki-gigaword-300', 'glove-twitter-25', 'glove-twitter-50', 'glove-twitter-100', 'glove-twitter-200', '__testing_word2vec-matrix-synopsis']


In [8]:
glove_vectors = gensim.downloader.load('word2vec-ruscorpora-300')

In [9]:
words=list(glove_vectors.vocab.keys())

In [10]:
cutsymbs=[":", "_"]
cleanwords=[]
for word in words:
    clean = word[0]
    i=0
    while word[i+1] not in cutsymbs:
        clean+=word[i+1]
        i+=1
    cleanwords.append(clean)

In [11]:
glove_vectors.most_similar('apple_NOUN')

[('microsoft_NOUN', 0.6669869422912598),
 ('ibm_NOUN', 0.6601744890213013),
 ('ipad_NOUN', 0.6473356485366821),
 ('неwlett::packard_NOUN', 0.6466790437698364),
 ('стив::джобс_NOUN', 0.6429045796394348),
 ('compaq_NOUN', 0.6296855807304382),
 ('macintosh_NOUN', 0.6265138387680054),
 ('lenovo_NOUN', 0.6258187294006348),
 ('motorola_NOUN', 0.6203649044036865),
 ('смартфон_NOUN', 0.6199597716331482)]

In [12]:
cleanwords

['весь',
 'человек',
 'мочь',
 'год',
 'сказать',
 'время',
 'говорить',
 'становиться',
 'знать',
 'самый',
 'дело',
 'день',
 'жизнь',
 'рука',
 'очень',
 'первый',
 'давать',
 'новый',
 'слово',
 'иметь',
 'большой',
 'идти',
 'глаз',
 'место',
 'лицо',
 'видеть',
 'хотеть',
 'понимать',
 'должный',
 'работа',
 'каждый',
 'друг',
 'голова',
 'дом',
 'оставаться',
 'сторона',
 'начинать',
 'думать',
 'хорошо',
 'жить',
 'стоять',
 'спрашивать',
 'сделать',
 'выходить',
 'последний',
 'русский',
 'сила',
 'получать',
 'какой-то',
 'хороший',
 'случай',
 'вопрос',
 'отвечать',
 'россия',
 'несколько',
 'мир',
 'город',
 'делать',
 'пойти',
 'приходить',
 'земля',
 'принимать',
 'часть',
 'вид',
 'ребенок',
 'конец',
 'взять',
 'всякий',
 'находить',
 'высокий',
 'сидеть',
 'что-то',
 'отец',
 'оказываться',
 'вода',
 'смотреть',
 'москва',
 'час',
 'являться',
 'народ',
 'любить',
 'проходить',
 'никто',
 'образ',
 'казаться',
 'женщина',
 'бог',
 'нога',
 'страна',
 'голос',
 'писать'

In [13]:
words

['весь_DET',
 'человек_NOUN',
 'мочь_VERB',
 'год_NOUN',
 'сказать_VERB',
 'время_NOUN',
 'говорить_VERB',
 'становиться_VERB',
 'знать_VERB',
 'самый_DET',
 'дело_NOUN',
 'день_NOUN',
 'жизнь_NOUN',
 'рука_NOUN',
 'очень_ADV',
 'первый_ADJ',
 'давать_VERB',
 'новый_ADJ',
 'слово_NOUN',
 'иметь_VERB',
 'большой_ADJ',
 'идти_VERB',
 'глаз_NOUN',
 'место_NOUN',
 'лицо_NOUN',
 'видеть_VERB',
 'хотеть_VERB',
 'понимать_VERB',
 'должный_ADJ',
 'работа_NOUN',
 'каждый_DET',
 'друг_NOUN',
 'голова_NOUN',
 'дом_NOUN',
 'оставаться_VERB',
 'сторона_NOUN',
 'начинать_VERB',
 'думать_VERB',
 'хорошо_ADV',
 'жить_VERB',
 'стоять_VERB',
 'спрашивать_VERB',
 'сделать_VERB',
 'выходить_VERB',
 'последний_ADJ',
 'русский_ADJ',
 'сила_NOUN',
 'получать_VERB',
 'какой-то_DET',
 'хороший_ADJ',
 'случай_NOUN',
 'вопрос_NOUN',
 'отвечать_VERB',
 'россия_NOUN',
 'несколько_NUM',
 'мир_NOUN',
 'город_NOUN',
 'делать_VERB',
 'пойти_VERB',
 'приходить_VERB',
 'земля_NOUN',
 'принимать_VERB',
 'часть_NOUN',
 'в

In [14]:
glove_vectors.get_vector('яблоко_NOUN')

array([ 4.16352339e-02,  6.44713938e-02, -8.55202153e-02, -5.79170734e-02,
        2.75890343e-02, -1.85643453e-02,  3.69282775e-02,  3.44568156e-02,
       -5.60245700e-02, -7.71315917e-02,  4.95299548e-02,  2.05855239e-02,
       -9.42526851e-03,  5.98796979e-02,  3.40499077e-03, -7.10126460e-02,
        6.99929744e-02, -2.77963970e-02,  5.57216667e-02,  1.29094543e-02,
       -7.05553293e-02, -1.35116447e-02, -2.56033782e-02,  5.25563210e-02,
       -3.90213281e-02, -5.32758087e-02,  9.78375375e-02, -1.09390117e-01,
       -3.11327670e-02, -5.42223044e-02,  6.16936348e-02,  7.93228820e-02,
        1.54521704e-01,  8.38155393e-03, -6.67934194e-02, -8.27612728e-03,
       -4.71919440e-02, -1.26785114e-01,  8.37007388e-02,  5.83530739e-02,
        7.30118230e-02, -1.16545719e-03,  4.21420373e-02, -4.30011339e-02,
        4.41543274e-02, -2.66371779e-02,  1.01740457e-01, -4.50710468e-02,
       -3.30404378e-03,  1.68887079e-02, -8.76717418e-02, -4.89782244e-02,
        4.23250161e-02,  

In [15]:
glove_vectors.get_vector(words[0]).shape

(300,)

In [16]:
fail300=np.ones(300)
fail300

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [17]:
def FindWordInVocab(word):
    word=word.lower()
    if word in cleanwords:
        index=cleanwords.index(word)
        return glove_vectors.get_vector(words[index])
    else:
        return fail300

In [18]:
FindWordInVocab("пень")

array([-0.05503651, -0.01098782,  0.12272408, -0.05566336, -0.02296354,
       -0.01249049,  0.0042192 ,  0.01577709, -0.0014821 , -0.09959209,
        0.01401108, -0.00632829, -0.01270246, -0.02603135, -0.02632509,
       -0.04140863,  0.02273068,  0.07624595,  0.09440958, -0.08012144,
        0.02840575,  0.07967015, -0.03172281,  0.04235531, -0.04205443,
       -0.05070185,  0.0946027 , -0.12558764, -0.10311361, -0.17685059,
        0.08767433,  0.06939302,  0.0877935 ,  0.01262966, -0.05018504,
       -0.0736531 ,  0.02371312,  0.05861176,  0.0867352 ,  0.02128221,
       -0.07059279,  0.00995665, -0.00173598, -0.09086753,  0.0120468 ,
        0.05240214,  0.10214973, -0.00914202,  0.04010548, -0.03125555,
        0.01918489, -0.02676721,  0.07261658, -0.03553908, -0.00810986,
       -0.04077101, -0.03736965,  0.02674667, -0.08494037, -0.05858091,
        0.05799918,  0.02053246,  0.05394483, -0.01696219, -0.00845756,
       -0.07931679, -0.05713269,  0.12517647, -0.108153  , -0.08

In [19]:
data=pd.read_json("data.json")

In [38]:
data

views  rating  votes  favorites  comments                    pubdate  \
0    21965      14     24          6        54  2020-11-14T15:00:41+00:00   
1     4669      23     23          6        18  2020-11-16T01:50:29+00:00   
2     1670      11     11          3        18  2020-11-15T21:14:23+00:00   
3     7411      19     19          7        37  2020-11-16T07:00:23+00:00   
4     1012       3      3          1         1  2020-11-16T07:52:15+00:00   
..     ...     ...    ...        ...       ...                        ...   
995  24252      47     51         33       103  2020-08-05T12:21:08+00:00   
996   4971       8      8          2        19  2020-08-05T11:56:54+00:00   
997   4127      11     11          2        27  2020-08-05T16:02:25+00:00   
998   8888       9     11          3        55  2020-08-05T17:00:11+00:00   
999   2650       8      8          3        20  2020-08-06T06:00:52+00:00   

                                                teaser  \
0    Разработчик бесплатного дополнения VS Code Sto...   
1    Старт Falcon 9 с кораблем Crew Dragon. Источни...   
2    Организация «Европейские цифровые права» (EDRi...   
3    По информации портала MacRumors, многие пользо...   
4    Qualcomm получила лицензию от правительства СШ...   
..                                                 ...   
995  Пользователи Windows 10 заметили, что программ...   
996  Пандемия коронавирусной инфекции COVID-19 вызв...   
997  Компания Google отключит своё музыкальное прил...   
998  5 августа 2020 года компания Facebook анонсиро...   
999  В конце июля 2020 года американское подразделе...   

                                                header  \
0    Дополнение VS Code Stories, добавляющее истори...   
1    НАСА и SpaceX успешно запустили первую регуляр...   
2    Организация «Европейские цифровые права» призы...   
3    Пользователи старых MacBook Pro жалуются, что ...   
4    Qualcomm получила разрешение властей США поста...   
..                                                 ...   
995  Microsoft Defender начал помечать файл hosts к...   
996  Мошенники начали массово создавать клоны Deliv...   
997  Google в октябре заменит Google Play Music на ...   
998  Instagram запустила Reels, своего конкурента T...   
999  Canon подверглась атаке вируса-вымогателя, сер...   

                                                  text  
0    Разработчик бесплатного дополнения VS Code Sto...  
1    Старт Falcon 9 с кораблем Crew Dragon. Источни...  
2    Организация «Европейские цифровые права» (EDRi...  
3    По информации портала MacRumors, многие пользо...  
4    Qualcomm получила лицензию от правительства СШ...  
..                                                 ...  
995  Пользователи Windows 10 заметили, что программ...  
996  <figure class="\n          \n          \n     ...  
997  <figure class="\n          \n          \n     ...  
998  5 августа 2020 года компания Facebook анонсиро...  
999  В конце июля 2020 года американское подразделе...  

[1000 rows x 9 columns]

In [43]:
wordlist = data["teaser"][0].split()
#list all the word in feature dataset (teasers)

In [48]:
def EncodeData(wordlist=wordlist):
    vector_words = []
    for word in wordlist:
        vector_words.append(FindWordInVocab(word))
    return vector_words
#Из списка слов делает вектор

In [49]:
ans=np.array(EncodeData())
print(ans.shape)

(47, 300)


In [46]:
len(wordlist)

47

In [24]:
import xgboost as xgb

In [25]:
#datetime.datetime(*ti.strptime("2007-03-04T21:08:12", "%Y-%m-%dT%H:%M:%S")[:6])

In [26]:
todrop=["pubdate", "text"]

In [27]:
for i in todrop:    
    data2=data.drop(i, axis=1)

In [28]:
data2=data2.drop("pubdate", axis=1)

In [29]:
from sklearn.model_selection import train_test_split

In [50]:
features = np.array(data2.drop("rating", axis=1))

In [58]:
features=data2["teaser"]
#features - это только текст тизеров

In [51]:
labels=np.array(data2["rating"])

In [59]:
features

0      Разработчик бесплатного дополнения VS Code Sto...
1      Старт Falcon 9 с кораблем Crew Dragon. Источни...
2      Организация «Европейские цифровые права» (EDRi...
3      По информации портала MacRumors, многие пользо...
4      Qualcomm получила лицензию от правительства СШ...
                             ...                        
995    Пользователи Windows 10 заметили, что программ...
996    Пандемия коронавирусной инфекции COVID-19 вызв...
997    Компания Google отключит своё музыкальное прил...
998    5 августа 2020 года компания Facebook анонсиро...
999    В конце июля 2020 года американское подразделе...
Name: teaser, Length: 1000, dtype: object

In [60]:
labels

array([ 14,  23,  11,  19,   3,   5,   3,   6,  -2,  14,   3,  12,  12,
        14,   4,  17,   5,  24,  16,   6,   1,  12,   4,  12,  21,   9,
         9,   3,   9,   6,   2,   3,   7,   5,   7,  17,   6,  19,   4,
         6,   6,   3,   3,  20,  16,   3,  16,   8,  29,   5,  11,   9,
         9,   9,   8,   5,  14,  15,  11,   6,  32,  11,   5,   5,   7,
        14,  14,  11,   4,   9,   8,  11,  28,  13,  10,   3,  12,   6,
         2,   4,  23,   7,  20,  51,  78,  14,  20,  14,  14,  12,  22,
        12,  26,  17,  24,  18,  41,  13,  23,  25,   7,  23,  32,  12,
         7,  11,   6,  15,  16,   5,   9,   7,  11,  25,  20,   2,   4,
        15,   9,   1,  14,  10,  12,  10,  30,  11,  15,  16,   9,   3,
        11,   5,   4,   3,   5,  29,  10,  28,  14,  55,  -2,  21,  13,
         6,   9,  14,  16,  23,  10,  17,   8,   9,   3,  61,  24,   6,
        13,  15,  -8,  50,  56,  34,  22,   8,  10,   7,   2,  15,   9,
        18,  16,  18,   7,  19,  30,   3,   9,  27,   9,  15,  2

Нужно из тизеров сделать числа, а потом передавать это как массив 1000 x 300, где 300 длина эмбеддинга

In [69]:
import re

In [87]:
reg = re.compile('[^а-яА-Я ^a-zA-Z]')
testcleanstr=reg.sub('', features[0])
testcleanstr

'Разработчик бесплатного дополнения VS Code Stories Бен Авад Ben Awad рассказал что принял решение расстаться с проектом почти сразу после его запуска Оказалось что он слишком понадеялся на честность и понимание пользователей и не учел их темную сторону в API проекта который по словам автора очень простой '

In [91]:
X=[]
reg = re.compile('[^а-яА-Я ^a-zA-Z]')
for str in features:
    X.append(reg.sub('', str))
X

['Разработчик бесплатного дополнения VS Code Stories Бен Авад Ben Awad рассказал что принял решение расстаться с проектом почти сразу после его запуска Оказалось что он слишком понадеялся на честность и понимание пользователей и не учел их темную сторону в API проекта который по словам автора очень простой ',
 'Старт Falcon  с кораблем Crew Dragon Источник фото НАСА ноября в  по московскому времени НАСА и SpaceX успешно осуществили запуск миссии Crew к МКС В первый регулярный полет на космическом корабле Crew Dragon отправились астронавты Майкл Хопкинс Виктор Гловер Шеннон Уокер и астронавт Японского агентства аэрокосмических исследований JAXA Соичи Ногучи',
 'Организация Европейские цифровые права EDRi запустила кампанию Верни свое лицо Reclaim Your Face Общественники призывают запретить повсеместное распространение технологии распознавания лиц и защитить личные данные граждан',
 'По информации портала MacRumors многие пользователи дюймовых ноутбуков MacBook Pro производства конца  го

In [94]:
X1=EncodeData(X[0])
X1
#Привести все слова в нач. форму, а дальше закодировать

[array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 

In [61]:
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.3, random_state=42)

In [62]:
X_train.shape

(700,)

In [36]:
model=xgb.XGBClassifier()

In [37]:
from sklearn.linear

SyntaxError: invalid syntax (<ipython-input-37-29a205309af6>, line 1)

In [ ]:
model.fit(X_train, y_train)

In [ ]:
predictions=model.predict(X_test)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot(predictions[:100], label="predticted views")
plt.plot(y_test[:100], label="true views")
plt.legend(bbox_to_anchor=(0., 1.02, 1., .102), loc='lower left',
           ncol=2, mode="expand", borderaxespad=0.)
plt.ylim(0, 50000)
#plt.ylegend()
plt.xlabel("Article Number")
plt.ylabel("Views")

In [ ]:
plt.plot(y_test)